### ISSUE TITLE
The resizing object jumping

### ISSUE THREAD

**Issue by kxbrand** [unlocomqx/jQuery-ui-resizable-rotation-patch#2]
When aspectRatio is true, or hold down the shift key, while stretching the NW position or SW position, the resizing object jumping

**Comment by karthickvkumar** [comment]
+1

**Comment by AshwinTayson** [comment]
Any fix found on this?

**Comment by unlocomqx** [comment]
Fixed in PR https://github.com/unlocomqx/jQuery-ui-resizable-rotation-patch/pull/4
